### ISSUE TITLE
Locator crashes when plotting

### ISSUE THREAD

**Issue by sceylan** [marsquakeservice/locator#1]
I work on mqsort virtual machine, and I do not know if this is already fixed. Locator crashes due to a floating number overflow in the frequency index variable while producing plots. Log message is below:

```
13:01:19 [warning] /bin/bash /home/sysop/mars/locator/m_locator.bash error log:
/home/sysop/mars/locator/locator/input.py:78: RuntimeWarning: divide by zero encountered in double_scalars
  idx_freq = np.argmin(abs(1./freqs[iphase] - periods))
/home/sysop/mars/locator/locator/graphics.py:127: RuntimeWarning: divide by zero encountered in double_scalars
  int(1./freqs[iax]))
Traceback (most recent call last):
  File "/home/sysop/mars/locator/main.py", line 85, in <module>
    plot_output=args.plot)
  File "/home/sysop/mars/locator/main.py", line 69, in main
    input['sigma'])
  File "/home/sysop/mars/locator/locator/graphics.py", line 127, in plot_phases
    int(1./freqs[iax]))
OverflowError: cannot convert float infinity to integer
```

**Comment by sstaehler** [comment]
You are probably using an input file without frequencies in the surface waves

Am 6. Dezember 2018 05:45:58 GMT-08:00 schrieb "Savas (Savash) Ceylan" <notifications@github.com>:
>I work on mqsort virtual machine, and I do not know if this is already
>fixed. Locator crashes due to a floating number overflow in the
>frequency index variable while producing plots. Log message is below:
>
>```
>13:01:19 [warning] /bin/bash /home/sysop/mars/locator/m_locator.bash
>error log:
>/home/sysop/mars/locator/locator/input.py:78: RuntimeWarning: divide by
>zero encountered in double_scalars
>  idx_freq = np.argmin(abs(1./freqs[iphase] - periods))
>/home/sysop/mars/locator/locator/graphics.py:127: RuntimeWarning:
>divide by zero encountered in double_scalars
>  int(1./freqs[iax]))
>Traceback (most recent call last):
>  File "/home/sysop/mars/locator/main.py", line 85, in <module>
>    plot_output=args.plot)
>  File "/home/sysop/mars/locator/main.py", line 69, in main
>    input['sigma'])
>File "/home/sysop/mars/locator/locator/graphics.py", line 127, in
>plot_phases
>    int(1./freqs[iax]))
>OverflowError: cannot convert float infinity to integer
>``` 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/marsquakeservice/locator/issues/1

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by sceylan** [comment]
Could be the case. We were acting too fast. Then I close the issue, and will re-open it if that's not case.
